[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/stream/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "frame-src https://vixsrc.to https://*.vixsrc.to 'self'; default-src * 'unsafe-inline' 'unsafe-eval' data: blob:;"
